Add Example description on README.md
nsoojin/baraba pull request #1
Opened 2020-03-17 06:45 UTC by jum0

I added Example description on README.md.

2020-03-17 12:46 UTC, nsoojin commented on README.md
> +3. Add `Privacy - Camera Usage Description` in the `info.plist`.
1,2번은 왜 필요한지 잘 모르겠습니다. 
샘플 앱은 바로 실행하면 되는데요.

3번도 여기 있으면 샘플 앱에 추가해야되는 것처럼 보일 수 있어서 Important 섹션 밑으로 들어가면 좋을거 같습니다.

2020-03-17 16:10 UTC, jum0 commented on README.md
> +3. Add `Privacy - Camera Usage Description` in the `info.plist`.
심플 앱 바로 실행되는 것 확인했습니다!

3번을 Important 섹션 하위로 옮겼는데, 수정할 부분 있으면 말씀 부탁드립니다!

2020-03-17 21:30 UTC, nsoojin commented on README.md
> +Before running the `Example` scheme, add `Privacy - Camera Usage Description` in the `info.plist`.
Example에는 Privacy 스트링이 이미 있습니다.
Example이 아니라 라이브러리를 넣으려고 하는 프로젝트에 추가를 해야합니다.

이런식으로는 어떤가요?
Don't forget to add `Privacy - Camera Usage Description` in your app's `info.plist` file.

2020-03-17 21:35 UTC, nsoojin requested changes
수정사항은 커밋 한개로 만들어주세요 😁

2020-03-18 06:30 UTC, jum0 commented on README.md
> +Before running the `Example` scheme, add `Privacy - Camera Usage Description` in the `info.plist`.
더 좋은 것 같습니다! 감사합니다!

2020-03-18 06:31 UTC, jum0 commented
수정 사항 커밋 하나로 만들었습니다😊

2020-03-18 15:43 UTC, nsoojin approved these changes

2020-03-18 15:46 UTC, merged